// Supabase Database Types
// This file is typically auto-generated by Supabase CLI
// For now, we'll define the structure manually

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          name: string | null;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
          subscription_plan: string;
          locale: string;
          created_default_items: boolean;
          preferences: Json | null;
          stats: Json | null;
        };
        Insert: {
          id?: string;
          email: string;
          name?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
          subscription_plan?: string;
          locale?: string;
          created_default_items?: boolean;
          preferences?: Json | null;
          stats?: Json | null;
        };
        Update: {
          id?: string;
          email?: string;
          name?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
          subscription_plan?: string;
          locale?: string;
          created_default_items?: boolean;
          preferences?: Json | null;
          stats?: Json | null;
        };
      };
      items: {
        Row: {
          id: string;
          user_id: string;
          title: string | null;
          category: string;
          colors: Json;
          material: string | null;
          style_tags: string[];
          season_tags: string[];
          image_local_path: string | null;
          image_hash: string | null;
          image_url: string | null;
          builtin_flag: boolean;
          metadata: Json | null;
          created_at: string;
          updated_at: string;
          last_worn_at: string | null;
          wear_count: number;
          is_favorite: boolean;
        };
        Insert: {
          id?: string;
          user_id: string;
          title?: string | null;
          category: string;
          colors?: Json;
          material?: string | null;
          style_tags?: string[];
          season_tags?: string[];
          image_local_path?: string | null;
          image_hash?: string | null;
          image_url?: string | null;
          builtin_flag?: boolean;
          metadata?: Json | null;
          created_at?: string;
          updated_at?: string;
          last_worn_at?: string | null;
          wear_count?: number;
          is_favorite?: boolean;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string | null;
          category?: string;
          colors?: Json;
          material?: string | null;
          style_tags?: string[];
          season_tags?: string[];
          image_local_path?: string | null;
          image_hash?: string | null;
          image_url?: string | null;
          builtin_flag?: boolean;
          metadata?: Json | null;
          created_at?: string;
          updated_at?: string;
          last_worn_at?: string | null;
          wear_count?: number;
          is_favorite?: boolean;
        };
      };
      outfits: {
        Row: {
          id: string;
          user_id: string | null;
          title: string | null;
          description: string | null;
          items: Json;
          background: Json;
          visibility: string;
          is_ai_generated: boolean;
          ai_metadata: Json | null;
          tags: string[] | null;
          styles: string[];
          seasons: string[];
          occasions: string[] | null;
          created_at: string;
          updated_at: string;
          last_worn_at: string | null;
          wear_count: number;
          is_favorite: boolean;
          likes_count: number;
          views_count: number;
          shares_count: number;
          canvas_settings: Json | null;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          title?: string | null;
          description?: string | null;
          items: Json;
          background?: Json;
          visibility?: string;
          is_ai_generated?: boolean;
          ai_metadata?: Json | null;
          tags?: string[] | null;
          styles?: string[];
          seasons?: string[];
          occasions?: string[] | null;
          created_at?: string;
          updated_at?: string;
          last_worn_at?: string | null;
          wear_count?: number;
          is_favorite?: boolean;
          likes_count?: number;
          views_count?: number;
          shares_count?: number;
          canvas_settings?: Json | null;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          title?: string | null;
          description?: string | null;
          items?: Json;
          background?: Json;
          visibility?: string;
          is_ai_generated?: boolean;
          ai_metadata?: Json | null;
          tags?: string[] | null;
          styles?: string[];
          seasons?: string[];
          occasions?: string[] | null;
          created_at?: string;
          updated_at?: string;
          last_worn_at?: string | null;
          wear_count?: number;
          is_favorite?: boolean;
          likes_count?: number;
          views_count?: number;
          shares_count?: number;
          canvas_settings?: Json | null;
        };
      };
      community_posts: {
        Row: {
          id: string;
          author_user_id: string;
          outfit_id: string | null;
          caption: string | null;
          images: string[] | null;
          tags: string[];
          mentions: string[];
          visibility: string;
          type: string;
          reactions_count: number;
          comments_count: number;
          shares_count: number;
          views_count: number;
          created_at: string;
          updated_at: string;
          edited_at: string | null;
          is_pinned: boolean;
          is_featured: boolean;
          is_sponsored: boolean;
          metadata: Json | null;
        };
        Insert: {
          id?: string;
          author_user_id: string;
          outfit_id?: string | null;
          caption?: string | null;
          images?: string[] | null;
          tags?: string[];
          mentions?: string[];
          visibility?: string;
          type?: string;
          reactions_count?: number;
          comments_count?: number;
          shares_count?: number;
          views_count?: number;
          created_at?: string;
          updated_at?: string;
          edited_at?: string | null;
          is_pinned?: boolean;
          is_featured?: boolean;
          is_sponsored?: boolean;
          metadata?: Json | null;
        };
        Update: {
          id?: string;
          author_user_id?: string;
          outfit_id?: string | null;
          caption?: string | null;
          images?: string[] | null;
          tags?: string[];
          mentions?: string[];
          visibility?: string;
          type?: string;
          reactions_count?: number;
          comments_count?: number;
          shares_count?: number;
          views_count?: number;
          created_at?: string;
          updated_at?: string;
          edited_at?: string | null;
          is_pinned?: boolean;
          is_featured?: boolean;
          is_sponsored?: boolean;
          metadata?: Json | null;
        };
      };
      subscriptions: {
        Row: {
          id: string;
          user_id: string;
          plan_type: string;
          status: string;
          started_at: string;
          expires_at: string | null;
          cancelled_at: string | null;
          paused_at: string | null;
          resume_at: string | null;
          provider_reference: string | null;
          payment_method: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          plan_type: string;
          status?: string;
          started_at?: string;
          expires_at?: string | null;
          cancelled_at?: string | null;
          paused_at?: string | null;
          resume_at?: string | null;
          provider_reference?: string | null;
          payment_method?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          plan_type?: string;
          status?: string;
          started_at?: string;
          expires_at?: string | null;
          cancelled_at?: string | null;
          paused_at?: string | null;
          resume_at?: string | null;
          provider_reference?: string | null;
          payment_method?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      ai_requests: {
        Row: {
          id: string;
          user_id: string;
          params: Json;
          result: Json | null;
          status: string;
          error_message: string | null;
          processing_time_ms: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          params: Json;
          result?: Json | null;
          status?: string;
          error_message?: string | null;
          processing_time_ms?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          params?: Json;
          result?: Json | null;
          status?: string;
          error_message?: string | null;
          processing_time_ms?: number | null;
          created_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
