/**
 * Tests for generateItemTitle utility
 */

import { ItemCategory, WardrobeItem } from '@/types/models/item';
import {
  generateItemTitle,
  getOrGenerateItemTitle,
  isAutoGeneratedTitle,
} from '../generateItemTitle';

// Mock wardrobe items factory
const createMockItem = (id: string, category: ItemCategory, title?: string): WardrobeItem => ({
  id,
  userId: 'user-1',
  title,
  category,
  colors: [{ hex: '#000000' }],
  primaryColor: { hex: '#000000' },
  styles: [],
  seasons: [],
  isBuiltin: false,
  createdAt: new Date(),
  updatedAt: new Date(),
  wearCount: 0,
  isFavorite: false,
});

describe('generateItemTitle', () => {
  it('should generate "Низ 1" for first bottoms item', () => {
    const result = generateItemTitle('bottoms', []);
    expect(result).toBe('Низ 1');
  });

  it('should generate "Верх 1" for first tops item', () => {
    const result = generateItemTitle('tops', []);
    expect(result).toBe('Верх 1');
  });

  it('should increment number based on existing items', () => {
    const existingItems: WardrobeItem[] = [
      createMockItem('1', 'bottoms', 'Низ 1'),
      createMockItem('2', 'bottoms', 'Низ 2'),
      createMockItem('3', 'bottoms', 'Низ 3'),
    ];

    const result = generateItemTitle('bottoms', existingItems);
    expect(result).toBe('Низ 4');
  });

  it('should find max number even with gaps', () => {
    const existingItems: WardrobeItem[] = [
      createMockItem('1', 'bottoms', 'Низ 1'),
      createMockItem('2', 'bottoms', 'Низ 10'),
      createMockItem('3', 'bottoms', 'Низ 5'),
    ];

    const result = generateItemTitle('bottoms', existingItems);
    expect(result).toBe('Низ 11');
  });

  it('should ignore items from other categories', () => {
    const existingItems: WardrobeItem[] = [
      createMockItem('1', 'tops', 'Верх 1'),
      createMockItem('2', 'tops', 'Верх 2'),
      createMockItem('3', 'bottoms', 'Низ 5'),
    ];

    const result = generateItemTitle('tops', existingItems);
    expect(result).toBe('Верх 3');
  });

  it('should ignore custom-named items', () => {
    const existingItems: WardrobeItem[] = [
      createMockItem('1', 'bottoms', 'Низ 1'),
      createMockItem('2', 'bottoms', 'Мои любимые джинсы'),
      createMockItem('3', 'bottoms', 'Низ 3'),
    ];

    const result = generateItemTitle('bottoms', existingItems);
    expect(result).toBe('Низ 4');
  });

  it('should handle items without titles', () => {
    const existingItems: WardrobeItem[] = [
      createMockItem('1', 'bottoms', undefined),
      createMockItem('2', 'bottoms', 'Низ 2'),
    ];

    const result = generateItemTitle('bottoms', existingItems);
    expect(result).toBe('Низ 3');
  });

  it('should work for all categories', () => {
    const categories: ItemCategory[] = [
      'headwear',
      'outerwear',
      'tops',
      'bottoms',
      'footwear',
      'accessories',
      'fullbody',
      'other',
    ];

    categories.forEach((category) => {
      const result = generateItemTitle(category, []);
      expect(result).toMatch(/^.+ 1$/);
    });
  });
});

describe('isAutoGeneratedTitle', () => {
  it('should return true for auto-generated titles', () => {
    expect(isAutoGeneratedTitle('Низ 1')).toBe(true);
    expect(isAutoGeneratedTitle('Верх 23')).toBe(true);
    expect(isAutoGeneratedTitle('Обувь 100')).toBe(true);
  });

  it('should return false for custom titles', () => {
    expect(isAutoGeneratedTitle('Мои джинсы')).toBe(false);
    expect(isAutoGeneratedTitle('Blue Sweater')).toBe(false);
    expect(isAutoGeneratedTitle('')).toBe(false);
    expect(isAutoGeneratedTitle(undefined)).toBe(false);
  });

  it('should check specific category when provided', () => {
    expect(isAutoGeneratedTitle('Низ 1', 'bottoms')).toBe(true);
    expect(isAutoGeneratedTitle('Низ 1', 'tops')).toBe(false);
  });
});

describe('getOrGenerateItemTitle', () => {
  const existingItems: WardrobeItem[] = [createMockItem('1', 'bottoms', 'Низ 5')];

  it('should use user title when provided', () => {
    const result = getOrGenerateItemTitle('My Jeans', 'bottoms', existingItems);
    expect(result).toBe('My Jeans');
  });

  it('should trim user title', () => {
    const result = getOrGenerateItemTitle('  My Jeans  ', 'bottoms', existingItems);
    expect(result).toBe('My Jeans');
  });

  it('should generate title when user title is empty', () => {
    const result = getOrGenerateItemTitle('', 'bottoms', existingItems);
    expect(result).toBe('Низ 6');
  });

  it('should generate title when user title is undefined', () => {
    const result = getOrGenerateItemTitle(undefined, 'bottoms', existingItems);
    expect(result).toBe('Низ 6');
  });

  it('should generate title when user title is only whitespace', () => {
    const result = getOrGenerateItemTitle('   ', 'bottoms', existingItems);
    expect(result).toBe('Низ 6');
  });
});
