// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application';

import AlertController from './alert_controller';
application.register('alert', AlertController);

import ClipboardController from './clipboard_controller';
application.register('clipboard', ClipboardController);

import ConfirmController from './confirm_controller';
application.register('confirm', ConfirmController);

import DropdownController from './dropdown_controller';
application.register('dropdown', DropdownController);

import FormController from './form_controller';
application.register('form', FormController);

import MobileMenuController from './mobile_menu_controller';
application.register('mobile-menu', MobileMenuController);

import ModalController from './modal_controller';
application.register('modal', ModalController);

import TabsController from './tabs_controller';
application.register('tabs', TabsController);
